### ISSUE TITLE
Ensure that Nabla can be deployed on Pendulum

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/wasm-deploy#45]
When deploying Nabla to Foucoco with the current deployment definition on branch `39-implement-tests-for-nabla-indexer`, then the fifth phase of the deployment scripts `06_deploy_swap_pools.ts` will not work as expected and some method calls will revert.

## How to reproduce
* check out branch `39-implement-tests-for-nabla-indexer`
* execute the following command in order to deploy Nabla to Foucoco: `npx ts-node src/index.ts deploy nabla --network foucoco`
* this will require you to enter the secret seed of the deployer account `6iFKMtX29zYoHRgDkPTXKuRsHRbJ3Gnaxyc4dRrZTANHvZi3`
* the script will now deploy Nabla to Foucoco, this will take many minutes as this requires many successive transactions
* part `nabla/deploy/06_deploy_swap_pools.ts` of the deployment scripts will then try to register the 5 swap pools with the router (this happens [here](https://github.com/pendulum-chain/wasm-deploy/blob/7e2d2140bd5a20b99056b8bcee9683b51d7d2654/nabla/deploy/06_deploy_swap_pools.ts#L94-L98))
* this will then call the method `registerPool` of the router contract, [once for each swap pool](https://github.com/pendulum-chain/wasm-deploy/blob/7e2d2140bd5a20b99056b8bcee9683b51d7d2654/nabla/_lib.ts#L23)
* it turns out that this call reverts and is not successful

## Alternative way to reproduce
Since the script runs very slowly, it is very time consuming to reproduce this call as it is occurs late in the deployment. In order to directly execute the call, you can instead use [this gist](https://gist.github.com/TorstenStueber/35e09ae5dec7670e1e9d68467022179c), which refers to an already existing partial deployment of Nabla, and:
* copy it into the root folder
* replace the place holder with the secret seed of the deployer account
* execute via `npx ts-node reproduce-nabla-deployment.ts`

The result will be
```
Result {
  execution: { type: 'onlyQuery' },
  result: { type: 'error', error: 'unknown' }
}
```
This means that the RPC call that is executed before the actual submission of the transaction (that is used as a dry run to determine gas fees) already fails. Closer inspection shows that the RPC returns with the following values:

* gasConsumed: `{"refTime":4403615014,"proofSize":100568}`
* gasRequired: `{"refTime":8131152627,"proofSize":203397}` 
* result: `{"ok":{"flags":["Revert"],"data":"0x"}}`

That means that the contract reverts without any further information.

## Context
This problem did not exist with the previous version of Nabla, which used commit `3e96787e161fb2657c90f18034691749647b691f` of https://github.com/0xamberhq/contracts.

It started to occur with the new necessary changes I added to Nabla that are now [on branch `pendulum-launch`](https://github.com/0xamberhq/contracts/tree/pendulum-launch).

All test have been adapted to that branch and run successfully. For that reason I assume that there is no inherent problem with that branch.

## Further assumptions
Looking at the definition of `registerPool` in the router contract, there are only a few places where the contract can revert:
* [some basic checks](https://github.com/0xamberhq/contracts/blob/8156960278e7e2eb18b1ca1fafffa18a94f03acc/contracts/src/core/Router.sol#L46-L48): but I checked that these conditions hold
* [the token approval chain extension call](https://github.com/0xamberhq/contracts/blob/8156960278e7e2eb18b1ca1fafffa18a94f03acc/contracts/src/core/Router.sol#L51): however, that worked properly in the previous version and the tokens in questions are actually allow listed

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/wasm-deploy/45?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by gianfra-t** [comment]
I will leave as a record the cause and solution found for this bug. 

The issue was caused by the changes introduced in this [PR](https://github.com/pendulum-chain/pendulum/pull/437) where the chain extensions definitions were refactored into using a [tuple](https://github.com/paritytech/substrate/blob/033d4e86cc7eff0066cd376b9375f815761d653c/frame/contracts/src/chain_extension.rs#L150) of chain extensions (one for Tokens, one for Prices). 

With this new changes, the way in which the id of the chain extension is called is also modified. Previously only the function identifier (defined [here](https://github.com/pendulum-chain/pendulum/pull/437/files#diff-eabf6a3163ad71f4a98413f7b76cda9ad0f21ceb1329fc4b7754af5b7068e0e3R50)) was enough to specify which chain extension method to call.

When using tuples, we also need to reference the ID of the chain extension element of the tuple (defined [here](https://github.com/pendulum-chain/pendulum/pull/437/files#diff-de2dd92164c67da5a95bb07625828adb228ea80718efd68c305e98cd6a643124R9)). This is done by concatenating the id as the 2 most significant bytes of the u32. The two less significant will be used to match the function of the specified extension.

Therefore in order to call function id `1100` of extension with ID `1` we need shift the ID 2 bytes and add it to the function id. In this example, it would be `66636`.

Ultimately, the failure to call the proper approve extension by the ERC20Wrapper resulted in the `unknown` error seen.

**Comment by TorstenStueber** [comment]
To add to this comment: the problem has been resolved through this PR: https://github.com/pendulum-chain/pendulum-solidity-wrapper/issues/42.

We can close this ticket now.
